apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-fastapi-recoservice-url
  namespace: default
type: Opaque
stringData:
  connstr: "Endpoint=sb://recobus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=cdZTIKRhvpizanc/vELLvKD5Iu7/OBscjxO6oRbIQhw="
  topic_name: "recotopic"
